name: Deploy to Google

on:
  push:
    branches:
      - main # Adjust as per your main branch name
permissions:
  contents: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
  Deploy_to_VM_google:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: SSH to VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            set -e                            
            cd ~/bot-noitu/bot-noi-tu
            git pull origin main              
            npm install --production --frozen-lockfile
            pm2 reload noi-tu --update-env || pm2 start bot.js --name noi-tu
            pm2 save
